[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["cd client && npm install --include=dev", "npm run client:build"]

[start]
cmd = "npm start"